### ISSUE TITLE
Decompressor returns -5 although decompresses everything or even more

### ISSUE THREAD

**Issue by tansy** [avaneev/lzav#2]
Tried that library and trying to decompress compressed data decompressor returned -5. Later investigation shown that it decompressed everything and even more.
With other string result was 100% correct decompression but function returned -5 as well.

```
#include <stdio.h>
#include <string.h>
#include "lzav.h"

int main()
{
    char input[] = "Which witch is which? Which witch is which?";
    char c_buf[100] = {0}, d_buf[100] = {0};
    int c_len, d_len;

    printf("'%s'\n", input);
    printf("strlen=%d\n", strlen(input));

    ///static inline int lzav_compress_default( const void* const src, void* const dst, const int srcl, const int dstl );
    c_len = lzav_compress_default(input, c_buf, strlen(input), sizeof(c_buf));
    printf("c_len=%d\n", c_len);

    d_len = lzav_decompress(c_buf, d_buf, c_len, sizeof(d_buf));
    printf("d_len=%d\n", d_len);

    printf("'%s'\n", d_buf);
    printf("strlen=%d\n", strlen(d_buf));
    ;
    return 0;
}
```

```
$ cc -o lzav-1cd lzav-1cd.c; ./lzav-1cd
'Which witch is which? Which witch is which?'
strlen=43
c_len=39
d_len=-5
'Which witch is which? Which witch is which? Whic'
strlen=48
```

**Comment by avaneev** [comment]
You have a bug in your code. The line
```
 d_len = lzav_decompress(c_buf, d_buf, c_len, sizeof(d_buf));
```
should really be
```
 d_len = lzav_decompress(c_buf, d_buf, c_len, strlen(input));
```

**Comment by avaneev** [comment]
LZAV does not add a header, it produces a raw compressed stream. The uncompressed data size should be known: this also provides an additional safety check. Parameter description for lzav_decompress() specifically notes that "dstl" is an expected destination data length.

**Comment by avaneev** [comment]
LZAV API is not equivalent to LZ4 nor Snappy. Expected decompressed length is usually always known in practice, because otherwise one can't allocate an in-memory buffer to hold all decompressed data.

**Comment by tansy** [comment]
You're right. For some reason I thought it was output buffer size. Sorry to bother.

That brings the question - it would be good to have some kind of 'end of steam' marker in case you don't know size of compressed steam. I know it's more like streaming feature, but still.

**Comment by avaneev** [comment]
I understand your point, but in that case a safety check against real destination size would not be possible. LZ77 stream is really an unnumerated sequence of blocks, so expected destination length should be stored somewhere anyway. I'm not implementing a header in LZAV, because it's more useful to leave that part implementation-specific. For example, a custom header may store CRC value along with source and destination lengths. In my opinion, both LZ4 and Snappy have an unnecessary overhead in that respect, because a programmer has to store compressed data length anyway, independent of such in-memory compressor - it's more reasonable to store it together with uncompressed data length.
